# Generated by Django 4.1.13 on 2025-11-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_entreprise",
                    models.CharField(
                        help_text="Le nom officiel de votre entreprise",
                        max_length=200,
                        verbose_name="Nom de l'entreprise",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True,
                        help_text="Le slogan de votre entreprise",
                        max_length=300,
                        null=True,
                        verbose_name="Slogan",
                    ),
                ),
                (
                    "adresse",
                    models.TextField(
                        help_text="Adresse complète de l'entreprise",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "ville",
                    models.CharField(
                        help_text="Ville où se trouve l'entreprise",
                        max_length=100,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        default="Haïti",
                        help_text="Pays où se trouve l'entreprise",
                        max_length=100,
                        verbose_name="Pays",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        help_text="Numéro de téléphone principal",
                        max_length=20,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "telephone_secondaire",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de téléphone secondaire (optionnel)",
                        max_length=20,
                        null=True,
                        verbose_name="Téléphone secondaire",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Adresse email de contact",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "site_web",
                    models.URLField(
                        blank=True,
                        help_text="URL du site web (optionnel)",
                        null=True,
                        verbose_name="Site web",
                    ),
                ),
                (
                    "numero_fiscal",
                    models.CharField(
                        blank=True,
                        help_text="Numéro fiscal/NIF de l'entreprise",
                        max_length=50,
                        null=True,
                        verbose_name="Numéro fiscal",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo de l'entreprise",
                        null=True,
                        upload_to="company/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="HTG",
                        help_text="Devise utilisée (HTG, USD, etc.)",
                        max_length=10,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration de l'entreprise",
                "verbose_name_plural": "Configuration de l'entreprise",
                "ordering": ["-updated_at"],
            },
        ),
    ]
