# Generated by Django 5.2.7 on 2025-10-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de création de l'enregistrement",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "numero_vente",
                    models.CharField(
                        help_text="Numéro unique de la vente",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de vente",
                    ),
                ),
                (
                    "client_nom",
                    models.CharField(
                        help_text="Nom du client",
                        max_length=200,
                        verbose_name="Nom du client",
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email du client",
                        max_length=254,
                        null=True,
                        verbose_name="Email du client",
                    ),
                ),
                (
                    "client_telephone",
                    models.CharField(
                        blank=True,
                        help_text="Téléphone du client",
                        max_length=20,
                        null=True,
                        verbose_name="Téléphone du client",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="EN_COURS",
                        help_text="Statut de la vente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_vente",
                    models.DateTimeField(
                        help_text="Date et heure de la vente",
                        verbose_name="Date de vente",
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Montant total de la vente",
                        max_digits=10,
                        verbose_name="Montant total",
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Montant de la remise",
                        max_digits=10,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "montant_final",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Montant final après remise",
                        max_digits=10,
                        verbose_name="Montant final",
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        default="ESPECES",
                        help_text="Mode de paiement",
                        max_length=50,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Commentaire sur la vente",
                        null=True,
                        verbose_name="Commentaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vente",
                "verbose_name_plural": "Ventes",
                "ordering": ["-date_vente"],
            },
        ),
        migrations.CreateModel(
            name="LigneVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de création de l'enregistrement",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(
                        help_text="Quantité vendue", verbose_name="Quantité"
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix unitaire au moment de la vente",
                        max_digits=10,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "montant_ligne",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total de la ligne",
                        max_digits=10,
                        verbose_name="Montant de la ligne",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        help_text="Produit vendu",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produits.produit",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        help_text="Vente associée",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="ventes.vente",
                        verbose_name="Vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de vente",
                "verbose_name_plural": "Lignes de vente",
                "ordering": ["id"],
            },
        ),
    ]
