# Generated by Django 5.2.7 on 2025-10-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de création de l'enregistrement",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de l'entreprise fournisseur",
                        max_length=200,
                        verbose_name="Nom du fournisseur",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        help_text="Nom du contact principal",
                        max_length=100,
                        verbose_name="Contact",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Adresse email du fournisseur",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        help_text="Numéro de téléphone",
                        max_length=20,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "adresse",
                    models.TextField(
                        help_text="Adresse complète du fournisseur",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "ville",
                    models.CharField(
                        help_text="Ville", max_length=100, verbose_name="Ville"
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        help_text="Code postal",
                        max_length=10,
                        verbose_name="Code postal",
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        default="France",
                        help_text="Pays",
                        max_length=100,
                        verbose_name="Pays",
                    ),
                ),
                (
                    "numero_tva",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de TVA intracommunautaire",
                        max_length=50,
                        null=True,
                        verbose_name="Numéro TVA",
                    ),
                ),
                (
                    "conditions_paiement",
                    models.CharField(
                        default="30 jours",
                        help_text="Conditions de paiement",
                        max_length=100,
                        verbose_name="Conditions de paiement",
                    ),
                ),
                (
                    "delai_livraison",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Délai de livraison en jours",
                        verbose_name="Délai de livraison (jours)",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Notes supplémentaires",
                        null=True,
                        verbose_name="Note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "ordering": ["nom"],
            },
        ),
    ]
