# Generated by Django 5.2.7 on 2025-10-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fournisseurs", "0001_initial"),
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de création de l'enregistrement",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("ENTREE", "Entrée"),
                            ("SORTIE", "Sortie"),
                            ("AJUSTEMENT", "Ajustement"),
                            ("RETOUR", "Retour"),
                        ],
                        help_text="Type de mouvement de stock",
                        max_length=20,
                        verbose_name="Type de mouvement",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(
                        help_text="Quantité concernée par le mouvement",
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("ACHAT", "Achat"),
                            ("VENTE", "Vente"),
                            ("AJUSTEMENT_INVENTAIRE", "Ajustement inventaire"),
                            ("RETOUR_CLIENT", "Retour client"),
                            ("RETOUR_FOURNISSEUR", "Retour fournisseur"),
                            ("CASSAGE", "Cassage"),
                            ("PERDU", "Perdu"),
                            ("VOL", "Vol"),
                            ("DON", "Don"),
                        ],
                        help_text="Motif du mouvement",
                        max_length=30,
                        verbose_name="Motif",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Référence du document (facture, bon de commande, etc.)",
                        max_length=100,
                        null=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix unitaire au moment du mouvement",
                        max_digits=10,
                        null=True,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True,
                        help_text="Client concerné (pour les sorties)",
                        max_length=200,
                        null=True,
                        verbose_name="Client",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Commentaire sur le mouvement",
                        null=True,
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "date_mouvement",
                    models.DateTimeField(
                        help_text="Date et heure du mouvement",
                        verbose_name="Date du mouvement",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fournisseur concerné (pour les entrées)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_stock",
                        to="fournisseurs.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        help_text="Produit concerné par le mouvement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements_stock",
                        to="produits.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-date_mouvement"],
            },
        ),
    ]
