# Generated by Django 5.2.7 on 2025-10-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fournisseurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de création de l'enregistrement",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de la catégorie de produit",
                        max_length=100,
                        verbose_name="Nom de la catégorie",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description de la catégorie",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Couleur hexadécimale pour l'affichage",
                        max_length=7,
                        verbose_name="Couleur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de création de l'enregistrement",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'enregistrement est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "code_produit",
                    models.CharField(
                        help_text="Code unique du produit",
                        max_length=50,
                        unique=True,
                        verbose_name="Code produit",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom du produit",
                        max_length=200,
                        verbose_name="Nom du produit",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée du produit",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix d'achat unitaire",
                        max_digits=10,
                        verbose_name="Prix d'achat",
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix de vente unitaire",
                        max_digits=10,
                        verbose_name="Prix de vente",
                    ),
                ),
                (
                    "unite",
                    models.CharField(
                        choices=[
                            ("PIECE", "Pièce"),
                            ("KG", "Kilogramme"),
                            ("L", "Litre"),
                            ("M", "Mètre"),
                            ("M2", "Mètre carré"),
                            ("M3", "Mètre cube"),
                            ("BOITE", "Boîte"),
                            ("PAQUET", "Paquet"),
                        ],
                        default="PIECE",
                        help_text="Unité de mesure du produit",
                        max_length=10,
                        verbose_name="Unité",
                    ),
                ),
                (
                    "seuil_alerte",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Seuil minimum pour déclencher une alerte",
                        verbose_name="Seuil d'alerte",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image du produit",
                        null=True,
                        upload_to="produits/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        help_text="Catégorie du produit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="produits.categorie",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "fournisseur_principal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fournisseur principal du produit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produits_principaux",
                        to="fournisseurs.fournisseur",
                        verbose_name="Fournisseur principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "ordering": ["nom"],
            },
        ),
    ]
